name: Comment and Merge PR
description: Posts a comment and merges the PR based on the assessment result
inputs:
  token:
    description: 'GitHub Token'
    required: true
  issue-number:
    description: 'Pull Request Number'
    required: true
  assessment:
    description: 'Assessment Result'
    required: true
  reason:
    description: 'Reason for Failure'
    required: false
runs:
  using: "composite"
  steps:
  - name: Post Comment
    if: inputs.assessment == 'true'
    shell: bash
    run: |
      curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.issue-number }}/comments \
        -d $(jq -n --arg body "🎉 Congratulations! You successfully completed step 1. Go back to the README in the main branch to continue." '{body: $body}')

  - name: Post Fail Comment
    if: inputs.assessment != 'true'
    shell: bash
    run: |
      curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.issue-number }}/comments \
        -d $(jq -n --arg body "🚫 The solution did not pass the validation check. Please try again. **Reason:** ${{ inputs.reason }}" '{body: $body}')

  - name: Merge PR
    if: inputs.assessment == 'true'
    shell: bash
    run: |
      gh pr merge ${{ inputs.issue-number }} --merge --admin --repo ${{ github.repository }}